theme:
  name: readthedocs
  # NOTE: syntax highlighting interfers with `signature_crossrefs` settings so we need to disable it, see:
  #   - https://github.com/mkdocstrings/mkdocstrings/issues/754
  highlightjs: false

site_name: Space Object Radar Tracking Simulator (SORTS)
nav:
- introduction.md
- installation.md
- configuration.md
- tutorial.md
- manual.md
- Examples: examples/
- API Reference: api_reference/
- Development:
  - Introduction: development/introduction.md

plugins:
- search
- gen-files:
    scripts:
    - scripts/gen_api_ref_pages.py
    - scripts/gen_examples_nav.py
- literate-nav:
    nav_file: nav.md
- section-index
- mkdocstrings:
    default_handler: python
    handlers:
      python:
        options:
          separate_signature: true
          show_signature_annotations: true
          signature_crossrefs: true
          show_overloads: true
- mkdocs-jupyter:
    execute: false # NOTE: tmp setting; for fast doc compilation until we actually work on examples
    include_source: True
    include: ["*.py","*.ipynb"]
    ignore: ["_wip*"]
