[project]
name = "sorts"
version = "0.1.0"
dynamic = [
    "description",
    "readme",
    "license",

    # TODO: migrate them to pyproject.toml ?
    # used in `setup.cfg`, but does not cause warnings/errors
    # "license-files"
    # "authors",
    # "classifiers",
    # "scripts",
    # "entry-points",

    # not used in setup.cfg
    # "maintainers",
    # "keywords",
    # "urls",
    # "gui-scripts",
]
requires-python = ">=3.11"
dependencies = [
    "h5py>=3.2.1",
    "matplotlib>=2.2.2",
    "numpy>=1.14.3",
    "scipy>=1.1.0",
    "sgp4>=2.7",
    "tabulate>=0.8.7",
    "tqdm>=4.46.0",
    "astropy>=4.1",
    "xmlschema>=1.5.1",
    "pyorb>=0.5.4",
    "pyant>=0.11.0",
    "yappi>=1.4.0",
    "requests>=2.32.3",
    "pandas>=2.2.3",
    "pyqt6>=6.8.1",
    "bokeh>=3.7.3",
    "jupyter-bokeh>=4.0.5",
    "jupyterlab>=4.4.4",
    "lets-plot>=4.6.2",
    "panel>=1.7.4",
    "pyproj>=3.7.1",
    "pyvista>=0.45.2",
]

[project.optional-dependencies]
spacetrack = ["spacetrack>=1.0.1"]
jupyter = [
    "ipykernel>=6.29.5",
    "ipywidgets>=8.1.7",
    "jupyter-bokeh>=4.0.5",
    "jupyterlab>=4.4.4",
]

[dependency-groups]
dev = [
    "pytest>=6.2.5",
    "sphinx>=4.2.0",
    "flake8>=4.0.1",
    "wheel>=0.37.0",
    "build>=0.7.0",
    "twine>=3.4.2",
    "pytest-cov>= 4.1.0",
    "sphinx-gallery>= 0.3.1",
    "matplotlib>=3.5.1",
    "nbsphinx>=0.8.8",
    "ipykernel>=6.9.1",
    "radon>=5.1.0",
    "numpydoc>=1.2",
    "pre-commit> 3.0.0",
    "black>=23.3.0",
    "auditwheel>=5.4.0",
    "patchelf>=0.14",
    "sphinx_panels>=0.6.0",
    "hawkmoth>=0.16.0",
    "watchfiles>=1.1.0",
    "sorts",
    "mkdocs>=1.6.1",
    "mkdocs-gen-files>=0.5.0",
]

[tool.setuptools.package-data]
sorts = ["py.typed"]

[tool.black]
line-length = 100

[tool.pytest.ini_options]
minversion = "6.0"
addopts = "-rp --capture=tee-sys"
log_format = "[%(asctime)s]%(levelname)s:%(name)s:%(message)s"
log_date_format = "%Y-%m-%d %H:%M:%S"
log_level = "INFO"
log_cli = true
testpaths = ["."]
python_functions = ["test_*", "*_test"]

[tool.uv.sources]
sorts = { workspace = true }
