from __future__ import annotations
import logging, typing as t
import pandas as pd
import xarray as xr
from sorts import types
from . import schedule_data_funcs, priority_scheduling


_K = schedule_data_funcs._K

logger = logging.getLogger(__name__)


XrDataArrayIndexer = xr.DataArray
"""Contains info to get a subset of entries from a `Schedule`"""


# TODO: add schedule validation?
class Schedule:
    """
    Provides methods for manipuating schedule data and enforce that the required columns/data are set.
    Also contains some related metadata.

    Schedule data is stored in the private attribute `_data`,
    and is not intended for consumption from outside of this library.

    NOTE:
        We are still evaluating which backing data structure to use and is subject to change
    """

    _K = schedule_data_funcs._K
    """shortcut to module attribute"""

    def __init__(self, data: schedule_data_funcs.ScheduleData):
        self._data = data

    @classmethod
    def from_ndarrays(cls, data: schedule_data_funcs.ScheduleNdarrayDict) -> t.Self:
        return cls(schedule_data_funcs.from_ndarrays(data))

    @classmethod
    def empty(cls) -> t.Self:
        return cls(data=schedule_data_funcs.empty_data())

    @classmethod
    def priority_scheduling(cls, schs: t.Sequence[Schedule]):
        """
        Merge a sequence of schedules for a single station into one,
        schedule with smaller index in the sequence is given priority over those with larger index.

        Note: It is assumed (and not checked) that each of the schedule itself does not contain overlapping entries.
        """

        if len(schs) == 0:
            logger.warning(
                f"An empty `Schedule` is being generated by `{priority_scheduling.__name__}`."
                + "This happens when an empty `Schedule` list is being passed as argument, which is usually not intended."
            )
            return cls.empty()

        resultant_sch_data = priority_scheduling.priority_scheduling([sch._data for sch in schs])

        return cls(data=resultant_sch_data)

    def to_ndarrays(self) -> schedule_data_funcs.ScheduleNdarrayDict:
        arr_dict = schedule_data_funcs.to_ndarrays(self._data)
        return arr_dict

    def to_dataframe(self) -> pd.DataFrame:
        return schedule_data_funcs.to_dataframe(self._data)

    def filter_by_time_range(self, time_range: types.TimeRange_us) -> t.Self:
        cls = type(self)
        filtered_data = schedule_data_funcs.filter_by_time_range(self._data, time_range)
        return cls(data=filtered_data)

    def filter_by_time_ranges(self, time_ranges: t.Sequence[types.TimeRange_us]) -> t.Self:
        cls = type(self)

        filtered_datas = schedule_data_funcs.filter_by_time_ranges(self._data, time_ranges)

        return cls(data=filtered_datas)

    # TODO: we can probably inject the schedule is tx or rx into `Schedule` class and remove param `is_split_simult`?
    def get_indexer_per_measurement(
        self, is_split_simult: bool, is_copy=False
    ) -> list[XrDataArrayIndexer]:
        return schedule_data_funcs.get_indexer_per_measurement(self._data, is_split_simult, is_copy)

    def get_experiment_detail(self, exp_num: int) -> schedule_data_funcs.ExperimentDetail:
        return self._data.attrs[_K.exp_detail_map][exp_num]
